### ISSUE TITLE
Déploiement et intégration continue

### ISSUE THREAD

**Issue by JeremD** [AntoineLabeeuw/app-legumes#13]
On met en production l'application avec Heroku et Travis ?

**Comment by WeirdRemora** [comment]
Yes !

**Comment by JeremD** [comment]
Je peux m'en charger si vous voulez

**Comment by AntoineLabeeuw** [comment]
J'ai fait une pull request(#23) pour travis, normalement tout est bon.

**Comment by AntoineLabeeuw** [comment]
J'ai fait une pull request(#23) pour travis, normalement tout est bon.

**Comment by JeremD** [comment]
Ok, vu
