### ISSUE TITLE
Page d'accueil

### ISSUE THREAD

**Issue by WeirdRemora** [AntoineLabeeuw/app-legumes#2]

**Comment by Gaelleb22** [comment]
Contient : Titre, barre de navigation, texte de présentation des légumes

**Comment by WeirdRemora** [comment]
> 
> 
> Contient : Titre, barre de navigation, texte de présentation des légumes

Non, la barre de navigation sera un component séparé

**Comment by JeremD** [comment]
Séparation des composants avec une grille Bootstrap.

**Comment by JeremD** [comment]
Image panier :
![panier](https://user-images.githubusercontent.com/22561974/90618938-eb1b2400-e210-11ea-9a36-5d103873dfa6.png)

**Comment by JeremD** [comment]
Image panier :
![panier](https://user-images.githubusercontent.com/22561974/90619062-1140c400-e211-11ea-9044-59dc7024c152.png)

**Comment by JeremD** [comment]
Page d'accueil terminée.
