### ISSUE TITLE
Barre de navigation non responsive

### ISSUE THREAD

**Issue by JeremD** [AntoineLabeeuw/app-legumes#26]
Le libellé du menu n’apparaît pas sur les petites résolutions d'écrans (cela concerne l’ensemble de l'app).
![bugmenu](https://user-images.githubusercontent.com/22561974/90634376-ddbd6400-e227-11ea-997a-ffea76a946b8.png)

**Comment by AntoineLabeeuw** [comment]
c'est a cause de la class="collapse"

**Comment by AntoineLabeeuw** [comment]
c'est a cause de la class="collapse"
