### ISSUE TITLE
Galerie : retirer description des légumes

### ISSUE THREAD

**Issue by Gaelleb22** [AntoineLabeeuw/app-legumes#35]

**Comment by JeremD** [comment]
@Gaelleb22 Je peux supprimer le texte sous chaque image ?

**Comment by Gaelleb22** [comment]
Oui, ça évitera les répétitions comme je vais faire un modal avec les descriptions.

**Comment by JeremD** [comment]
Super, je m'en charge.

**Comment by JeremD** [comment]
@Gaelleb22 Comme ceci ?
![image](https://user-images.githubusercontent.com/22561974/90649565-2a5e6a80-e23b-11ea-9dea-074f3fa6a10c.png)

**Comment by Gaelleb22** [comment]
Parfait !
